#!/usr/bin/env bash
# exam-to-qti.sh - Convert exam markdown to Canvas QTI format
# Generated by flow-cli teaching framework
# Requires: examark (npm install -g examark)

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ============================================================================
# VALIDATION
# ============================================================================

# Check examark installed
if ! command -v examark &>/dev/null; then
  echo -e "${RED}❌ examark not installed${NC}"
  echo ""
  echo "Install examark:"
  echo -e "  ${BLUE}npm install -g examark${NC}"
  echo ""
  echo "Documentation:"
  echo "  https://github.com/daveagp/examark"
  exit 1
fi

# Check input file provided
if [[ $# -eq 0 ]]; then
  echo -e "${RED}❌ No input file specified${NC}"
  echo ""
  echo "Usage: $0 <exam-file.md>"
  echo ""
  echo "Examples:"
  echo "  $0 exams/midterm1.md"
  echo "  $0 exams/final.md"
  exit 1
fi

EXAM_FILE="$1"

# Check file exists
if [[ ! -f "$EXAM_FILE" ]]; then
  echo -e "${RED}❌ File not found: $EXAM_FILE${NC}"
  exit 1
fi

# Check file is markdown
if [[ ! "$EXAM_FILE" =~ \.md$ ]]; then
  echo -e "${YELLOW}⚠️  Warning: File does not have .md extension${NC}"
  echo "Continue anyway? [y/N]"
  read -r continue
  if [[ "$continue" != "y" ]]; then
    echo "Cancelled"
    exit 1
  fi
fi

# ============================================================================
# CONVERSION
# ============================================================================

echo ""
echo -e "${BLUE}🔄 Converting exam to Canvas QTI...${NC}"
echo ""
echo "Input:  $EXAM_FILE"

# Generate output filename
OUTPUT_FILE="${EXAM_FILE%.md}.zip"
echo "Output: $OUTPUT_FILE"
echo ""

# Run examark conversion
# examark uses Canvas QTI 1.2 format by default
if examark "$EXAM_FILE" 2>&1; then
  # Count questions (examark creates a zip file)
  if [[ -f "$OUTPUT_FILE" ]]; then
    # Try to get question count from zip contents
    QUESTION_COUNT=$(unzip -l "$OUTPUT_FILE" 2>/dev/null | grep -c '<item' || echo "?")

    echo ""
    echo -e "${GREEN}✅ Converted successfully${NC}"
    echo ""
    echo "Output file: ${BLUE}$OUTPUT_FILE${NC}"

    if [[ "$QUESTION_COUNT" != "?" ]]; then
      echo "Questions:   ~$QUESTION_COUNT"
    fi

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo -e "${GREEN}Upload to Canvas:${NC}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "1. Go to your Canvas course"
    echo "2. Navigate to: Quizzes"
    echo "3. Click: Import"
    echo "4. Select: QTI 1.2/1.1 Package"
    echo "5. Upload: $OUTPUT_FILE"
    echo "6. Click: Import"
    echo ""
    echo -e "${YELLOW}Note: Review and edit questions in Canvas after import${NC}"
    echo ""
  else
    echo ""
    echo -e "${YELLOW}⚠️  Conversion completed but output file not found${NC}"
    echo "Expected: $OUTPUT_FILE"
    exit 1
  fi
else
  echo ""
  echo -e "${RED}❌ Conversion failed${NC}"
  echo ""
  echo "Common issues:"
  echo "  - Invalid markdown format"
  echo "  - Missing frontmatter (---, title, ---)"
  echo "  - Incorrect question syntax"
  echo ""
  echo "Check examark documentation:"
  echo "  https://github.com/daveagp/examark"
  echo ""
  echo "Example question format:"
  echo "  1. [5 pts] Question text?"
  echo "     - [ ] Option A"
  echo "     - [x] Option B (correct)"
  echo "     - [ ] Option C"
  exit 1
fi
