#!/usr/bin/env bash
# Quick Deploy - Single commit to production
# Generated by flow-cli teaching framework

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Load course config
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG="$PROJECT_DIR/.flow/teach-config.yml"

if [[ ! -f "$CONFIG" ]]; then
  echo -e "${RED}❌ Config not found: $CONFIG${NC}"
  exit 1
fi

# Validate yq available
if ! command -v yq &>/dev/null; then
  echo -e "${RED}❌ yq is required${NC}"
  echo -e "${YELLOW}Install: brew install yq${NC}"
  exit 1
fi

# Read config
DRAFT_BRANCH=$(yq -r '.branches.draft' "$CONFIG")
PRODUCTION_BRANCH=$(yq -r '.branches.production' "$CONFIG")
SITE_URL=$(yq -r '.deployment.web.url' "$CONFIG")

# Safety check
CURRENT_BRANCH=$(git branch --show-current)
if [[ "$CURRENT_BRANCH" != "$DRAFT_BRANCH" ]]; then
  echo -e "${RED}❌ Must be on $DRAFT_BRANCH branch${NC}"
  echo -e "${YELLOW}Current branch: $CURRENT_BRANCH${NC}"
  echo -e "${BLUE}Run: git checkout $DRAFT_BRANCH${NC}"
  exit 1
fi

# Check for uncommitted changes
if ! git diff-index --quiet HEAD --; then
  echo -e "${YELLOW}⚠️  Uncommitted changes detected${NC}"
  read -p "Commit changes first? [Y/n] " commit_first

  if [[ "$commit_first" != "n" ]]; then
    read -p "Commit message: " commit_msg
    git add .
    git commit -m "${commit_msg:-Quick update}"
  else
    echo -e "${RED}❌ Cannot deploy with uncommitted changes${NC}"
    exit 1
  fi
fi

# Quick deploy
echo ""
echo -e "${BLUE}🚀 Quick Deploy: $DRAFT_BRANCH → $PRODUCTION_BRANCH${NC}"
echo ""

# Record start time
START_TIME=$(date +%s)

# Switch to production
git checkout "$PRODUCTION_BRANCH"

# Merge draft
echo -e "${YELLOW}Merging draft...${NC}"
if ! git merge "$DRAFT_BRANCH" --no-edit; then
  echo -e "${RED}❌ Merge conflict detected${NC}"
  echo -e "${YELLOW}Resolve conflicts and run again${NC}"
  git merge --abort
  git checkout "$DRAFT_BRANCH"
  exit 1
fi

# Push to remote
echo -e "${YELLOW}Pushing to remote...${NC}"
git push origin "$PRODUCTION_BRANCH"

# Switch back to draft
git checkout "$DRAFT_BRANCH"

# Calculate duration
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Deployed to production in ${DURATION}s${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}🌐 Site: $SITE_URL${NC}"
echo -e "${YELLOW}⏳ GitHub Actions deploying (usually < 2 min)${NC}"
echo ""
echo -e "${BLUE}💡 Tip: Check deployment status at:${NC}"
echo -e "   https://github.com/$(git config --get remote.origin.url | sed 's/.*github.com[:\/]\(.*\)\.git/\1/')/actions"
echo ""
