#!/usr/bin/env bash
# Semester Archive - Annual transition helper
# Generated by flow-cli teaching framework

set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

# Load config
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG="$PROJECT_DIR/.flow/teach-config.yml"

if [[ ! -f "$CONFIG" ]]; then
  echo -e "${RED}❌ Config not found: $CONFIG${NC}"
  exit 1
fi

# Validate yq available
if ! command -v yq &>/dev/null; then
  echo -e "${RED}❌ yq is required${NC}"
  echo -e "${YELLOW}Install: brew install yq${NC}"
  exit 1
fi

SEMESTER=$(yq -r '.course.semester' "$CONFIG")
YEAR=$(yq -r '.course.year' "$CONFIG")
TAG="$SEMESTER-$YEAR-final"

echo "📋 Semester Archive Tool"
echo ""
echo "  Semester: $SEMESTER $YEAR"
echo "  Tag: $TAG"
echo ""

read -p "Create archive tag? [Y/n] " confirm
if [[ "$confirm" == "n" ]]; then
  exit 0
fi

# Tag production branch
PRODUCTION_BRANCH=$(yq -r '.branches.production' "$CONFIG")
git checkout "$PRODUCTION_BRANCH"
git tag -a "$TAG" -m "$SEMESTER $YEAR - Course Complete"
git push --tags

echo ""
echo -e "${GREEN}✅ Archived: $TAG${NC}"
echo ""
echo -e "${BLUE}📝 Next steps:${NC}"
echo "   1. Update .flow/teach-config.yml for next semester"
echo "   2. Update course.year (or course.semester)"
echo "   3. Commit config changes to draft branch"
echo ""
