# Markdown Lint Configuration for flow-cli
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# MD003: Heading style
MD003:
  style: 'atx' # Use ### style, not underline style

# MD004: Unordered list style
MD004:
  style: 'dash' # Use - for lists, not * or +

# MD007: Unordered list indentation
MD007:
  indent: 2 # 2 spaces per indent level
  start_indented: false

# MD010: No hard tabs
MD010:
  code_blocks: false # Allow tabs in code blocks only

# MD012: Multiple consecutive blank lines
MD012:
  maximum: 2 # Allow up to 2 blank lines

# MD013: Line length
MD013:
  line_length: 120 # Max 120 chars (mkdocs Material default)
  code_blocks: false # Don't enforce in code blocks
  tables: false # Don't enforce in tables
  headings: false # Don't enforce in headings
  heading_line_length: 120

# MD022: Headings should be surrounded by blank lines
MD022:
  lines_above: 1
  lines_below: 1

# MD024: Multiple headings with the same content
MD024:
  siblings_only: true # Allow same heading in different sections

# MD025: Multiple top-level headings in the same document
MD025:
  level: 1 # Only one # heading per document
  front_matter_title: ''

# MD026: Trailing punctuation in heading
MD026:
  punctuation: '.,;:!' # Don't allow these at end of headings

# MD029: Ordered list item prefix
MD029:
  style: 'ordered' # Use 1. 2. 3., not 1. 1. 1.

# MD033: Inline HTML
MD033:
  allowed_elements:
    - details # Allow <details> for collapsible sections
    - summary # Allow <summary> for collapsible headers
    - br # Allow <br> for line breaks
    - table # Allow HTML tables
    - tr # Allow table rows
    - td # Allow table data
    - th # Allow table headers
    - img # Allow images with attributes
    - a # Allow links with attributes
    - div # Allow divs for Material admonitions

# MD034: Bare URL used
MD034: false # Allow bare URLs

# MD036: Emphasis used instead of a heading
MD036:
  punctuation: '.,;:!?'

# MD040: Fenced code blocks should have a language specified
MD040:
  allowed_languages: []
  language_only: false

# MD041: First line in a file should be a top-level heading
MD041:
  level: 1
  front_matter_title: ''

# MD046: Code block style
MD046:
  style: 'fenced' # Use ``` style, not indented

# MD048: Code fence style
MD048:
  style: 'backtick' # Use ```, not ~~~

# MD049: Emphasis style
MD049:
  style: 'asterisk' # Use *italic* and **bold**

# MD050: Strong style
MD050:
  style: 'asterisk' # Use **bold**, not __bold__

# Disabled rules (too strict for documentation)
MD001: false # Heading levels increment by one - we sometimes skip levels in docs
MD005: false # Inconsistent indentation for list items - allow flexibility
MD014: false # Dollar signs used before commands - we show shell prompts
MD028: false # Blank line inside blockquote - allow for readability
MD030: false # Spaces after list markers - allow flexibility
MD032: false # Lists should be surrounded by blank lines - allow flexibility
MD042: false # No empty links - sometimes used as placeholders
