#!/usr/bin/env zsh
# Pre-push hook for Quarto teaching projects
# Auto-generated by: teach hooks install
# Version: 1.0.0
# DO NOT EDIT - This file is managed by flow-cli

# ============================================================================
# CONFIGURATION
# ============================================================================

# Colors for output
typeset -gA COLORS
COLORS=(
  [reset]='\033[0m'
  [bold]='\033[1m'
  [success]='\033[38;5;114m'
  [warning]='\033[38;5;221m'
  [error]='\033[38;5;203m'
  [info]='\033[38;5;117m'
  [muted]='\033[38;5;245m'
)

# Protected branches that require _site/ to be built
typeset -a PROTECTED_BRANCHES
PROTECTED_BRANCHES=(
  "main"
  "production"
  "gh-pages"
)

# ============================================================================
# LOGGING HELPERS
# ============================================================================

_log_success() { echo -e "${COLORS[success]}✓ $*${COLORS[reset]}" }
_log_warning() { echo -e "${COLORS[warning]}⚠ $*${COLORS[reset]}" }
_log_error()   { echo -e "${COLORS[error]}✗ $*${COLORS[reset]}" }
_log_info()    { echo -e "${COLORS[info]}ℹ $*${COLORS[reset]}" }
_log_muted()   { echo -e "${COLORS[muted]}$*${COLORS[reset]}" }

# ============================================================================
# PRODUCTION BRANCH VALIDATION
# ============================================================================

_check_production_branch() {
  local remote="$1"
  local url="$2"
  local local_ref="$3"
  local local_sha="$4"
  local remote_ref="$5"
  local remote_sha="$6"

  # Extract branch name from ref (refs/heads/main -> main)
  local branch="${local_ref#refs/heads/}"

  # Check if this is a protected branch
  local is_protected=0
  for protected in "${PROTECTED_BRANCHES[@]}"; do
    if [[ "$branch" == "$protected" ]]; then
      is_protected=1
      break
    fi
  done

  if [[ $is_protected -eq 0 ]]; then
    return 0  # Not a protected branch, allow push
  fi

  _log_info "Validating push to protected branch: ${COLORS[bold]}$branch${COLORS[reset]}"

  # Check 1: Verify _site/ directory exists
  if [[ ! -d "_site" ]]; then
    _log_error "Cannot push to $branch: _site/ directory not found"
    _log_muted "   Protected branches require a built site"
    _log_info "   Run: ${COLORS[bold]}quarto render${COLORS[reset]}"
    return 1
  fi

  # Check 2: Verify _site/ contains index.html
  if [[ ! -f "_site/index.html" ]]; then
    _log_error "Cannot push to $branch: _site/index.html not found"
    _log_muted "   Site appears incomplete or corrupted"
    _log_info "   Run: ${COLORS[bold]}quarto render${COLORS[reset]}"
    return 1
  fi

  # Check 3: Verify _site/ is not empty (has at least 3 files)
  local site_files
  site_files=$(find _site -type f | wc -l)
  if [[ $site_files -lt 3 ]]; then
    _log_error "Cannot push to $branch: _site/ appears empty ($site_files files)"
    _log_info "   Run: ${COLORS[bold]}quarto render${COLORS[reset]}"
    return 1
  fi

  # Check 4: Verify _site/ was built recently (within last 24 hours)
  if [[ -f "_site/index.html" ]]; then
    local site_age
    site_age=$(( $(date +%s) - $(stat -f %m "_site/index.html" 2>/dev/null || echo 0) ))
    local hours=$((site_age / 3600))

    if [[ $hours -gt 24 ]]; then
      _log_warning "_site/index.html is $hours hours old"
      _log_muted "   Consider rebuilding before push"

      # Prompt for confirmation
      local response
      read -t 10 "response?Continue push anyway? [y/N] " 2>/dev/null
      if [[ ! "$response" =~ ^[Yy]$ ]]; then
        _log_info "Push aborted"
        return 1
      fi
    fi
  fi

  # Check 5: Verify no _freeze/ files are being pushed
  local freeze_files
  freeze_files=$(git diff --name-only "$remote_sha..$local_sha" 2>/dev/null | grep '^_freeze/' || true)

  if [[ -n "$freeze_files" ]]; then
    _log_error "Cannot push to $branch: _freeze/ files detected in commit"
    _log_muted "   Files:"
    echo "$freeze_files" | while read -r f; do
      _log_muted "     - $f"
    done
    _log_info "   To remove: ${COLORS[bold]}git rm --cached -r _freeze/${COLORS[reset]}"
    return 1
  fi

  _log_success "Production validation passed for $branch"
  return 0
}

# ============================================================================
# BRANCH-SPECIFIC CHECKS
# ============================================================================

_check_draft_branch() {
  local branch="$1"

  # Draft branches (draft/*, feature/*, dev) allow more flexibility
  if [[ "$branch" =~ ^(draft|feature|dev) ]]; then
    _log_info "Draft branch detected: $branch"
    _log_muted "   Skipping strict production checks"
    return 0
  fi

  return 1  # Not a draft branch
}

# ============================================================================
# QUARTO PROJECT VALIDATION
# ============================================================================

_validate_quarto_project() {
  # Check if this is a Quarto project
  if [[ ! -f "_quarto.yml" ]]; then
    _log_muted "Not a Quarto project - skipping validation"
    return 0
  fi

  # Verify quarto is installed
  if ! command -v quarto &>/dev/null; then
    _log_warning "Quarto not found - skipping project validation"
    return 0
  fi

  # Check if _quarto.yml is valid
  if ! quarto inspect . &>/dev/null; then
    _log_error "_quarto.yml appears invalid"
    _log_info "   Run: ${COLORS[bold]}quarto inspect .${COLORS[reset]}"
    return 1
  fi

  return 0
}

# ============================================================================
# MAIN HOOK EXECUTION
# ============================================================================

main() {
  echo ""
  _log_info "${COLORS[bold]}Pre-push validation${COLORS[reset]}"
  echo ""

  # Check if this is a Quarto project
  if ! _validate_quarto_project; then
    return 1
  fi

  # Git pre-push hook receives input on stdin:
  # <local ref> <local sha> <remote ref> <remote sha>
  local validation_errors=0

  while read local_ref local_sha remote_ref remote_sha; do
    # Skip if deleting remote branch (local_sha is all zeros)
    if [[ "$local_sha" == "0000000000000000000000000000000000000000" ]]; then
      continue
    fi

    # Extract branch name
    local branch="${local_ref#refs/heads/}"

    _log_info "Checking branch: ${COLORS[bold]}$branch${COLORS[reset]}"

    # Check if this is a draft/feature branch (more lenient)
    if _check_draft_branch "$branch"; then
      _log_success "Draft branch validation passed"
      continue
    fi

    # Production branch validation
    if ! _check_production_branch "$1" "$2" "$local_ref" "$local_sha" "$remote_ref" "$remote_sha"; then
      ((validation_errors++))
    fi
  done

  echo ""

  if [[ $validation_errors -gt 0 ]]; then
    _log_error "Pre-push validation failed with $validation_errors error(s)"
    _log_info "Push blocked - fix errors and try again"
    return 1
  fi

  _log_success "All pre-push validations passed"
  return 0
}

# Execute main function
main "$@"
exit $?
