#!/usr/bin/env zsh
# Prepare-commit-msg hook for Quarto teaching projects
# Auto-generated by: teach hooks install
# Version: 1.0.0
# DO NOT EDIT - This file is managed by flow-cli

# ============================================================================
# CONFIGURATION
# ============================================================================

# Enable validation timing in commit messages (default: on)
QUARTO_COMMIT_TIMING="${QUARTO_COMMIT_TIMING:-1}"

# Enable validation summary in commit messages (default: off)
QUARTO_COMMIT_SUMMARY="${QUARTO_COMMIT_SUMMARY:-0}"

# ============================================================================
# MAIN HOOK EXECUTION
# ============================================================================

main() {
  local commit_msg_file="$1"
  local commit_source="$2"
  local commit_sha="$3"

  # Only modify messages for regular commits (not merges, squashes, etc.)
  if [[ -n "$commit_source" ]] && [[ "$commit_source" != "message" ]]; then
    return 0
  fi

  # Skip if timing is disabled
  if [[ "${QUARTO_COMMIT_TIMING}" != "1" ]]; then
    return 0
  fi

  # Get validation timing from temporary file (created by pre-commit hook)
  local timing_file="/tmp/flow-quarto-validation-timing-$$"
  if [[ ! -f "$timing_file" ]]; then
    # No timing data available - skip
    return 0
  fi

  local validation_time
  validation_time=$(cat "$timing_file" 2>/dev/null || echo "0")
  rm -f "$timing_file"

  # Skip if no validation was performed
  if [[ "$validation_time" == "0" ]]; then
    return 0
  fi

  # Read current commit message
  local current_msg
  current_msg=$(cat "$commit_msg_file")

  # Check if timing annotation already exists
  if echo "$current_msg" | grep -q '^\[validation:'; then
    return 0
  fi

  # Append validation timing
  local timing_note
  if [[ "${QUARTO_COMMIT_SUMMARY}" == "1" ]]; then
    # Get validation summary from temporary file
    local summary_file="/tmp/flow-quarto-validation-summary-$$"
    if [[ -f "$summary_file" ]]; then
      local summary
      summary=$(cat "$summary_file")
      rm -f "$summary_file"
      timing_note="[validation: ${validation_time}s] $summary"
    else
      timing_note="[validation: ${validation_time}s]"
    fi
  else
    timing_note="[validation: ${validation_time}s]"
  fi

  # Append to commit message (after main message, before comments)
  {
    echo "$current_msg"
    echo ""
    echo "$timing_note"
  } > "$commit_msg_file"

  return 0
}

# Execute main function
main "$@"
exit $?
