# lib/config.zsh - Configuration management for flow-cli
# Handles reading/writing config values and profile management

# ============================================================================
# CONFIGURATION PATHS
# ============================================================================

# Main config file
FLOW_CONFIG_FILE="${FLOW_CONFIG_DIR}/config.zsh"

# Profile directory
FLOW_PROFILE_DIR="${FLOW_CONFIG_DIR}/profiles"

# Default config values (used if not set)
typeset -gA FLOW_CONFIG_DEFAULTS=(
  # Core settings
  [projects_root]="$HOME/projects"
  [atlas_enabled]="auto"
  [load_dispatchers]="yes"
  [quiet]="0"
  [debug]="0"

  # UI settings
  [color_theme]="default"
  [progress_bar_width]="10"
  [show_icons]="yes"

  # Timer defaults
  [timer_default]="25"
  [timer_break]="5"
  [timer_long_break]="15"
  [timer_sound]="yes"

  # ADHD settings
  [auto_breadcrumb]="yes"
  [session_timeout]="120"
  [dopamine_mode]="yes"

  # Git settings
  [auto_commit]="no"
  [commit_emoji]="yes"
  [push_after_finish]="ask"

  # AI settings
  [ai_provider]="claude"
  [ai_model]="sonnet"
  [ai_context]="auto"
  [ai_verbose]="no"
)

# Current config values (loaded from file)
typeset -gA FLOW_CONFIG=()

# ============================================================================
# CONFIG FILE MANAGEMENT
# ============================================================================

# Initialize config system
_flow_config_init() {
  # Ensure config directory exists
  [[ ! -d "$FLOW_CONFIG_DIR" ]] && mkdir -p "$FLOW_CONFIG_DIR"
  [[ ! -d "$FLOW_PROFILE_DIR" ]] && mkdir -p "$FLOW_PROFILE_DIR"

  # Load config if exists
  if [[ -f "$FLOW_CONFIG_FILE" ]]; then
    _flow_config_load
  else
    # Use defaults
    FLOW_CONFIG=("${(@kv)FLOW_CONFIG_DEFAULTS}")
  fi
}

# Load config from file
_flow_config_load() {
  if [[ ! -f "$FLOW_CONFIG_FILE" ]]; then
    return 1
  fi

  # Start with defaults
  FLOW_CONFIG=("${(@kv)FLOW_CONFIG_DEFAULTS}")

  # Source the config file (it sets FLOW_CONFIG values)
  source "$FLOW_CONFIG_FILE" 2>/dev/null

  return 0
}

# Save config to file
_flow_config_save() {
  local config_dir="${FLOW_CONFIG_FILE:h}"
  [[ ! -d "$config_dir" ]] && mkdir -p "$config_dir"

  # Write header
  cat > "$FLOW_CONFIG_FILE" <<'EOF'
# flow-cli configuration
# Generated by: flow config
# Edit with: flow config edit
#
# Format: FLOW_CONFIG[key]="value"
# Run 'flow config show' to see all options

EOF

  # Write config values (sorted by key)
  local key
  for key in "${(@ko)FLOW_CONFIG}"; do
    local value="${FLOW_CONFIG[$key]}"
    # Only write if different from default or if it's a user-modified value
    echo "FLOW_CONFIG[$key]=\"$value\"" >> "$FLOW_CONFIG_FILE"
  done

  # Add timestamp
  echo "" >> "$FLOW_CONFIG_FILE"
  echo "# Last modified: $(date -Iseconds)" >> "$FLOW_CONFIG_FILE"
}

# ============================================================================
# CONFIG VALUE ACCESSORS
# ============================================================================

# Get a config value
# Usage: _flow_config_get "key" ["default"]
_flow_config_get() {
  local key="$1"
  local default="${2:-${FLOW_CONFIG_DEFAULTS[$key]:-}}"

  echo "${FLOW_CONFIG[$key]:-$default}"
}

# Set a config value
# Usage: _flow_config_set "key" "value"
_flow_config_set() {
  local key="$1"
  local value="$2"

  # Validate key exists in defaults (known key)
  if [[ -z "${FLOW_CONFIG_DEFAULTS[$key]+isset}" ]]; then
    # Allow custom keys with warning
    [[ -n "${FLOW_DEBUG:-}" ]] && _flow_log_warning "Unknown config key: $key"
  fi

  FLOW_CONFIG[$key]="$value"
}

# Reset a config value to default
# Usage: _flow_config_reset "key"
_flow_config_reset() {
  local key="$1"

  if [[ -n "${FLOW_CONFIG_DEFAULTS[$key]+isset}" ]]; then
    FLOW_CONFIG[$key]="${FLOW_CONFIG_DEFAULTS[$key]}"
    return 0
  else
    return 1
  fi
}

# Reset all config to defaults
_flow_config_reset_all() {
  FLOW_CONFIG=("${(@kv)FLOW_CONFIG_DEFAULTS}")
}

# Check if a config value is set (not default)
_flow_config_is_set() {
  local key="$1"
  [[ "${FLOW_CONFIG[$key]:-}" != "${FLOW_CONFIG_DEFAULTS[$key]:-}" ]]
}

# ============================================================================
# CONFIG DISPLAY
# ============================================================================

# Show all config values
_flow_config_show() {
  local filter="${1:-}"
  local show_all="${2:-false}"

  echo ""
  echo "${FLOW_COLORS[header]}FLOW-CLI CONFIGURATION${FLOW_COLORS[reset]}"
  echo ""

  # Group configs by category
  local -A categories=(
    [core]="projects_root atlas_enabled load_dispatchers quiet debug"
    [ui]="color_theme progress_bar_width show_icons"
    [timer]="timer_default timer_break timer_long_break timer_sound"
    [adhd]="auto_breadcrumb session_timeout dopamine_mode"
    [git]="auto_commit commit_emoji push_after_finish"
    [ai]="ai_provider ai_context ai_verbose"
  )

  local -a category_order=(core ui timer adhd git ai)

  for category in "${category_order[@]}"; do
    local keys="${categories[$category]}"
    local -a key_list=(${=keys})

    # Skip if filter doesn't match category
    if [[ -n "$filter" && "$category" != *"$filter"* ]]; then
      local match=false
      for key in "${key_list[@]}"; do
        [[ "$key" == *"$filter"* ]] && match=true && break
      done
      [[ "$match" == "false" ]] && continue
    fi

    echo "  ${FLOW_COLORS[bold]}${category:u}${FLOW_COLORS[reset]}"

    for key in "${key_list[@]}"; do
      # Skip if filter doesn't match
      if [[ -n "$filter" && "$key" != *"$filter"* && "$category" != *"$filter"* ]]; then
        continue
      fi

      local value="${FLOW_CONFIG[$key]:-${FLOW_CONFIG_DEFAULTS[$key]:-}}"
      local default="${FLOW_CONFIG_DEFAULTS[$key]:-}"
      local modified=""

      if [[ "$value" != "$default" ]]; then
        modified=" ${FLOW_COLORS[accent]}*${FLOW_COLORS[reset]}"
      fi

      printf "    %-20s = %s%s\n" "$key" "$value" "$modified"
    done
    echo ""
  done

  echo "${FLOW_COLORS[muted]}  * = modified from default${FLOW_COLORS[reset]}"
  echo "${FLOW_COLORS[muted]}  Config file: $FLOW_CONFIG_FILE${FLOW_COLORS[reset]}"
  echo ""
}

# Show config in export format
_flow_config_export() {
  for key in "${(@ko)FLOW_CONFIG}"; do
    echo "FLOW_CONFIG[$key]=\"${FLOW_CONFIG[$key]}\""
  done
}

# ============================================================================
# CONFIG PROFILES
# ============================================================================

# List available profiles
_flow_config_profile_list() {
  echo ""
  echo "${FLOW_COLORS[header]}CONFIGURATION PROFILES${FLOW_COLORS[reset]}"
  echo ""

  # Built-in profiles
  echo "  ${FLOW_COLORS[bold]}Built-in:${FLOW_COLORS[reset]}"
  echo "    minimal     - Minimal settings, quiet mode"
  echo "    developer   - Full developer settings"
  echo "    adhd        - Maximum ADHD support features"
  echo "    researcher  - Academic workflow optimized"
  echo ""

  # User profiles
  if [[ -d "$FLOW_PROFILE_DIR" ]] && [[ -n "$(ls -A "$FLOW_PROFILE_DIR" 2>/dev/null)" ]]; then
    echo "  ${FLOW_COLORS[bold]}User Profiles:${FLOW_COLORS[reset]}"
    for profile in "$FLOW_PROFILE_DIR"/*.zsh(N); do
      local name="${${profile:t}%.zsh}"
      local modified=$(stat -f "%Sm" -t "%Y-%m-%d" "$profile" 2>/dev/null || echo "unknown")
      echo "    $name (saved: $modified)"
    done
  else
    echo "  ${FLOW_COLORS[muted]}No user profiles saved${FLOW_COLORS[reset]}"
    echo "  ${FLOW_COLORS[muted]}Create with: flow config profile save <name>${FLOW_COLORS[reset]}"
  fi
  echo ""
}

# Save current config as profile
# Usage: _flow_config_profile_save "name"
_flow_config_profile_save() {
  local name="$1"

  if [[ -z "$name" ]]; then
    _flow_log_error "Profile name required"
    return 1
  fi

  # Validate name
  if [[ ! "$name" =~ ^[a-zA-Z][a-zA-Z0-9_-]*$ ]]; then
    _flow_log_error "Invalid profile name. Use letters, numbers, hyphens, underscores."
    return 1
  fi

  # Don't overwrite built-in profile names
  if [[ "$name" == "minimal" || "$name" == "developer" || "$name" == "adhd" || "$name" == "researcher" ]]; then
    _flow_log_error "Cannot overwrite built-in profile: $name"
    return 1
  fi

  local profile_file="$FLOW_PROFILE_DIR/$name.zsh"

  [[ ! -d "$FLOW_PROFILE_DIR" ]] && mkdir -p "$FLOW_PROFILE_DIR"

  # Write profile
  cat > "$profile_file" <<EOF
# flow-cli profile: $name
# Created: $(date -Iseconds)
# Load with: flow config profile load $name

EOF

  for key in "${(@ko)FLOW_CONFIG}"; do
    echo "FLOW_CONFIG[$key]=\"${FLOW_CONFIG[$key]}\"" >> "$profile_file"
  done

  _flow_log_success "Saved profile: $name"
  echo "  Location: $profile_file"
}

# Load a profile
# Usage: _flow_config_profile_load "name"
_flow_config_profile_load() {
  local name="$1"

  if [[ -z "$name" ]]; then
    _flow_log_error "Profile name required"
    return 1
  fi

  # Handle built-in profiles
  case "$name" in
    minimal)
      _flow_config_reset_all
      FLOW_CONFIG[quiet]="1"
      FLOW_CONFIG[show_icons]="no"
      FLOW_CONFIG[dopamine_mode]="no"
      FLOW_CONFIG[auto_breadcrumb]="no"
      _flow_log_success "Loaded built-in profile: minimal"
      ;;
    developer)
      _flow_config_reset_all
      FLOW_CONFIG[load_dispatchers]="yes"
      FLOW_CONFIG[auto_commit]="no"
      FLOW_CONFIG[commit_emoji]="yes"
      FLOW_CONFIG[ai_context]="auto"
      _flow_log_success "Loaded built-in profile: developer"
      ;;
    adhd)
      _flow_config_reset_all
      FLOW_CONFIG[dopamine_mode]="yes"
      FLOW_CONFIG[auto_breadcrumb]="yes"
      FLOW_CONFIG[show_icons]="yes"
      FLOW_CONFIG[timer_default]="25"
      FLOW_CONFIG[timer_break]="5"
      FLOW_CONFIG[session_timeout]="90"
      _flow_log_success "Loaded built-in profile: adhd"
      ;;
    researcher)
      _flow_config_reset_all
      FLOW_CONFIG[timer_default]="45"
      FLOW_CONFIG[timer_break]="10"
      FLOW_CONFIG[session_timeout]="180"
      FLOW_CONFIG[push_after_finish]="no"
      _flow_log_success "Loaded built-in profile: researcher"
      ;;
    *)
      # Load user profile
      local profile_file="$FLOW_PROFILE_DIR/$name.zsh"

      if [[ ! -f "$profile_file" ]]; then
        _flow_log_error "Profile not found: $name"
        echo "  Available profiles:"
        _flow_config_profile_list
        return 1
      fi

      # Reset to defaults first
      _flow_config_reset_all

      # Source the profile
      source "$profile_file"
      _flow_log_success "Loaded profile: $name"
      ;;
  esac

  echo ""
  echo "${FLOW_COLORS[muted]}Run 'flow config save' to persist changes${FLOW_COLORS[reset]}"
}

# Delete a user profile
# Usage: _flow_config_profile_delete "name"
_flow_config_profile_delete() {
  local name="$1"

  if [[ -z "$name" ]]; then
    _flow_log_error "Profile name required"
    return 1
  fi

  # Don't delete built-in profiles
  if [[ "$name" == "minimal" || "$name" == "developer" || "$name" == "adhd" || "$name" == "researcher" ]]; then
    _flow_log_error "Cannot delete built-in profile: $name"
    return 1
  fi

  local profile_file="$FLOW_PROFILE_DIR/$name.zsh"

  if [[ ! -f "$profile_file" ]]; then
    _flow_log_error "Profile not found: $name"
    return 1
  fi

  rm "$profile_file"
  _flow_log_success "Deleted profile: $name"
}

# ============================================================================
# INTERACTIVE CONFIG
# ============================================================================

# Interactive config wizard
_flow_config_wizard() {
  echo ""
  echo "${FLOW_COLORS[header]}🔧 FLOW-CLI CONFIGURATION WIZARD${FLOW_COLORS[reset]}"
  echo ""
  echo "This wizard will help you configure flow-cli."
  echo "Press Enter to keep the current value."
  echo ""

  # Core settings
  echo "${FLOW_COLORS[bold]}CORE SETTINGS${FLOW_COLORS[reset]}"

  local current value

  # Projects root
  current="${FLOW_CONFIG[projects_root]}"
  echo -n "  Projects root [$current]: "
  read -r value
  [[ -n "$value" ]] && FLOW_CONFIG[projects_root]="$value"

  # Atlas enabled
  current="${FLOW_CONFIG[atlas_enabled]}"
  echo -n "  Atlas integration (auto/yes/no) [$current]: "
  read -r value
  [[ -n "$value" ]] && FLOW_CONFIG[atlas_enabled]="$value"

  # Quiet mode
  current="${FLOW_CONFIG[quiet]}"
  echo -n "  Quiet mode (0/1) [$current]: "
  read -r value
  [[ -n "$value" ]] && FLOW_CONFIG[quiet]="$value"

  echo ""
  echo "${FLOW_COLORS[bold]}TIMER SETTINGS${FLOW_COLORS[reset]}"

  # Timer default
  current="${FLOW_CONFIG[timer_default]}"
  echo -n "  Default timer (minutes) [$current]: "
  read -r value
  [[ -n "$value" ]] && FLOW_CONFIG[timer_default]="$value"

  # Break timer
  current="${FLOW_CONFIG[timer_break]}"
  echo -n "  Break timer (minutes) [$current]: "
  read -r value
  [[ -n "$value" ]] && FLOW_CONFIG[timer_break]="$value"

  echo ""
  echo "${FLOW_COLORS[bold]}ADHD SETTINGS${FLOW_COLORS[reset]}"

  # Dopamine mode
  current="${FLOW_CONFIG[dopamine_mode]}"
  echo -n "  Dopamine mode (yes/no) [$current]: "
  read -r value
  [[ -n "$value" ]] && FLOW_CONFIG[dopamine_mode]="$value"

  # Auto breadcrumb
  current="${FLOW_CONFIG[auto_breadcrumb]}"
  echo -n "  Auto breadcrumb (yes/no) [$current]: "
  read -r value
  [[ -n "$value" ]] && FLOW_CONFIG[auto_breadcrumb]="$value"

  echo ""
  echo "${FLOW_COLORS[bold]}GIT SETTINGS${FLOW_COLORS[reset]}"

  # Push after finish
  current="${FLOW_CONFIG[push_after_finish]}"
  echo -n "  Push after finish (yes/no/ask) [$current]: "
  read -r value
  [[ -n "$value" ]] && FLOW_CONFIG[push_after_finish]="$value"

  # Commit emoji
  current="${FLOW_CONFIG[commit_emoji]}"
  echo -n "  Use emoji in commits (yes/no) [$current]: "
  read -r value
  [[ -n "$value" ]] && FLOW_CONFIG[commit_emoji]="$value"

  echo ""

  # Save
  if _flow_confirm "Save configuration?"; then
    _flow_config_save
    _flow_log_success "Configuration saved!"
  else
    echo "Configuration not saved. Changes will be lost on shell restart."
  fi
}

# ============================================================================
# APPLY CONFIG TO ENVIRONMENT
# ============================================================================

# Apply config values to environment variables
_flow_config_apply() {
  # Map config values to environment variables
  export FLOW_PROJECTS_ROOT="${FLOW_CONFIG[projects_root]:-$HOME/projects}"
  export FLOW_ATLAS_ENABLED="${FLOW_CONFIG[atlas_enabled]:-auto}"
  export FLOW_LOAD_DISPATCHERS="${FLOW_CONFIG[load_dispatchers]:-yes}"

  [[ "${FLOW_CONFIG[quiet]}" == "1" ]] && export FLOW_QUIET=1
  [[ "${FLOW_CONFIG[debug]}" == "1" ]] && export FLOW_DEBUG=1
}

# ============================================================================
# INITIALIZATION
# ============================================================================

# Auto-initialize on source
_flow_config_init
