# lib/config.zsh - Configuration management for flow-cli
# Handles reading/writing config values and profile management

# ============================================================================
# CONFIGURATION PATHS
# ============================================================================

# Main config file
FLOW_CONFIG_FILE="${FLOW_CONFIG_DIR}/config.zsh"

# Profile directory
FLOW_PROFILE_DIR="${FLOW_CONFIG_DIR}/profiles"

# Default config values (used if not set)
typeset -gA FLOW_CONFIG_DEFAULTS=(
  # Core settings
  [projects_root]="$HOME/projects"
  [atlas_enabled]="auto"
  [load_dispatchers]="yes"
  [quiet]="0"
  [debug]="0"

  # UI settings
  [color_theme]="default"
  [progress_bar_width]="10"
  [show_icons]="yes"

  # Timer defaults
  [timer_default]="25"
  [timer_break]="5"
  [timer_long_break]="15"
  [timer_sound]="yes"

  # ADHD settings
  [auto_breadcrumb]="yes"
  [session_timeout]="120"
  [dopamine_mode]="yes"

  # Git settings
  [auto_commit]="no"
  [commit_emoji]="yes"
  [push_after_finish]="ask"

  # AI settings
  [ai_provider]="claude"
  [ai_model]="sonnet"
  [ai_context]="auto"
  [ai_verbose]="no"
)

# Current config values (loaded from file)
typeset -gA FLOW_CONFIG=()

# ============================================================================
# CONFIG FILE MANAGEMENT
# ============================================================================

# =============================================================================
# Function: _flow_config_init
# Purpose: Initialize the configuration system and load existing config
# =============================================================================
# Arguments:
#   None
#
# Returns:
#   0 - Always succeeds
#
# Output:
#   None
#
# Side Effects:
#   - Creates FLOW_CONFIG_DIR if it doesn't exist
#   - Creates FLOW_PROFILE_DIR if it doesn't exist
#   - Populates FLOW_CONFIG associative array from file or defaults
#
# Example:
#   _flow_config_init
#
# Notes:
#   - Called automatically when lib/config.zsh is sourced
#   - If config file exists, loads values via _flow_config_load
#   - If no config file, uses FLOW_CONFIG_DEFAULTS
# =============================================================================
_flow_config_init() {
  # Ensure config directory exists
  [[ ! -d "$FLOW_CONFIG_DIR" ]] && mkdir -p "$FLOW_CONFIG_DIR"
  [[ ! -d "$FLOW_PROFILE_DIR" ]] && mkdir -p "$FLOW_PROFILE_DIR"

  # Load config if exists
  if [[ -f "$FLOW_CONFIG_FILE" ]]; then
    _flow_config_load
  else
    # Use defaults
    FLOW_CONFIG=("${(@kv)FLOW_CONFIG_DEFAULTS}")
  fi
}

# =============================================================================
# Function: _flow_config_load
# Purpose: Load configuration values from the config file
# =============================================================================
# Arguments:
#   None
#
# Returns:
#   0 - Config file loaded successfully
#   1 - Config file does not exist
#
# Output:
#   None
#
# Side Effects:
#   - Resets FLOW_CONFIG to defaults first
#   - Sources FLOW_CONFIG_FILE to override with saved values
#
# Example:
#   _flow_config_load
#   if [[ $? -eq 0 ]]; then
#     echo "Config loaded"
#   fi
#
# Notes:
#   - Always starts with defaults before loading file
#   - Errors from sourcing are suppressed (2>/dev/null)
#   - Config file format: FLOW_CONFIG[key]="value"
# =============================================================================
_flow_config_load() {
  if [[ ! -f "$FLOW_CONFIG_FILE" ]]; then
    return 1
  fi

  # Start with defaults
  FLOW_CONFIG=("${(@kv)FLOW_CONFIG_DEFAULTS}")

  # Source the config file (it sets FLOW_CONFIG values)
  source "$FLOW_CONFIG_FILE" 2>/dev/null

  return 0
}

# =============================================================================
# Function: _flow_config_save
# Purpose: Save current configuration values to the config file
# =============================================================================
# Arguments:
#   None
#
# Returns:
#   0 - Always succeeds (file write assumed successful)
#
# Output:
#   Writes to FLOW_CONFIG_FILE
#
# Side Effects:
#   - Creates config directory if it doesn't exist
#   - Overwrites existing config file
#   - Adds header comment and timestamp
#
# Example:
#   FLOW_CONFIG[quiet]="1"
#   _flow_config_save
#
# Notes:
#   - Keys are written in sorted order for consistency
#   - All current FLOW_CONFIG values are saved (including defaults)
#   - File format is sourceable ZSH (FLOW_CONFIG[key]="value")
#   - Adds ISO-8601 timestamp at end of file
# =============================================================================
_flow_config_save() {
  local config_dir="${FLOW_CONFIG_FILE:h}"
  [[ ! -d "$config_dir" ]] && mkdir -p "$config_dir"

  # Write header
  cat > "$FLOW_CONFIG_FILE" <<'EOF'
# flow-cli configuration
# Generated by: flow config
# Edit with: flow config edit
#
# Format: FLOW_CONFIG[key]="value"
# Run 'flow config show' to see all options

EOF

  # Write config values (sorted by key)
  local key
  for key in "${(@ko)FLOW_CONFIG}"; do
    local value="${FLOW_CONFIG[$key]}"
    # Only write if different from default or if it's a user-modified value
    echo "FLOW_CONFIG[$key]=\"$value\"" >> "$FLOW_CONFIG_FILE"
  done

  # Add timestamp
  echo "" >> "$FLOW_CONFIG_FILE"
  echo "# Last modified: $(date -Iseconds)" >> "$FLOW_CONFIG_FILE"
}

# ============================================================================
# CONFIG VALUE ACCESSORS
# ============================================================================

# =============================================================================
# Function: _flow_config_get
# Purpose: Retrieve a configuration value by key with optional default
# =============================================================================
# Arguments:
#   $1 - (required) Configuration key name
#   $2 - (optional) Default value if key not set [default: from FLOW_CONFIG_DEFAULTS]
#
# Returns:
#   0 - Always succeeds
#
# Output:
#   stdout - The configuration value or default
#
# Example:
#   timer=$(_flow_config_get "timer_default")
#   # => "25"
#
#   theme=$(_flow_config_get "unknown_key" "fallback")
#   # => "fallback"
#
# Notes:
#   - First checks FLOW_CONFIG array
#   - Falls back to provided default or FLOW_CONFIG_DEFAULTS
#   - Never returns empty if key exists in defaults
# =============================================================================
_flow_config_get() {
  local key="$1"
  local default="${2:-${FLOW_CONFIG_DEFAULTS[$key]:-}}"

  echo "${FLOW_CONFIG[$key]:-$default}"
}

# =============================================================================
# Function: _flow_config_set
# Purpose: Set a configuration value in memory
# =============================================================================
# Arguments:
#   $1 - (required) Configuration key name
#   $2 - (required) Value to set
#
# Returns:
#   0 - Always succeeds
#
# Output:
#   stderr - Warning if unknown key (when FLOW_DEBUG is set)
#
# Side Effects:
#   - Updates FLOW_CONFIG associative array
#   - Does NOT persist to file (call _flow_config_save separately)
#
# Example:
#   _flow_config_set "timer_default" "30"
#   _flow_config_set "custom_key" "value"  # Warns in debug mode
#
# Notes:
#   - Allows setting unknown keys (for extensibility)
#   - Warns about unknown keys when FLOW_DEBUG is enabled
#   - Changes are in-memory only until _flow_config_save is called
# =============================================================================
_flow_config_set() {
  local key="$1"
  local value="$2"

  # Validate key exists in defaults (known key)
  if [[ -z "${FLOW_CONFIG_DEFAULTS[$key]+isset}" ]]; then
    # Allow custom keys with warning
    [[ -n "${FLOW_DEBUG:-}" ]] && _flow_log_warning "Unknown config key: $key"
  fi

  FLOW_CONFIG[$key]="$value"
}

# =============================================================================
# Function: _flow_config_reset
# Purpose: Reset a single configuration value to its default
# =============================================================================
# Arguments:
#   $1 - (required) Configuration key to reset
#
# Returns:
#   0 - Key was found in defaults and reset
#   1 - Key not found in FLOW_CONFIG_DEFAULTS
#
# Output:
#   None
#
# Side Effects:
#   - Updates FLOW_CONFIG[$key] to default value
#   - Does NOT persist to file (call _flow_config_save separately)
#
# Example:
#   _flow_config_reset "timer_default"
#   # FLOW_CONFIG[timer_default] is now "25" (the default)
#
# Notes:
#   - Only works for known keys (defined in FLOW_CONFIG_DEFAULTS)
#   - Returns error for unknown/custom keys
# =============================================================================
_flow_config_reset() {
  local key="$1"

  if [[ -n "${FLOW_CONFIG_DEFAULTS[$key]+isset}" ]]; then
    FLOW_CONFIG[$key]="${FLOW_CONFIG_DEFAULTS[$key]}"
    return 0
  else
    return 1
  fi
}

# =============================================================================
# Function: _flow_config_reset_all
# Purpose: Reset all configuration values to their defaults
# =============================================================================
# Arguments:
#   None
#
# Returns:
#   0 - Always succeeds
#
# Output:
#   None
#
# Side Effects:
#   - Replaces entire FLOW_CONFIG array with FLOW_CONFIG_DEFAULTS
#   - Any custom keys are lost
#   - Does NOT persist to file (call _flow_config_save separately)
#
# Example:
#   _flow_config_reset_all
#   _flow_config_save  # Persist the reset
#
# Notes:
#   - Destructive operation - all customizations are lost
#   - Custom keys (not in defaults) are removed entirely
#   - Used by profile loading to ensure clean slate
# =============================================================================
_flow_config_reset_all() {
  FLOW_CONFIG=("${(@kv)FLOW_CONFIG_DEFAULTS}")
}

# =============================================================================
# Function: _flow_config_is_set
# Purpose: Check if a configuration value differs from its default
# =============================================================================
# Arguments:
#   $1 - (required) Configuration key to check
#
# Returns:
#   0 - Value is different from default (user-modified)
#   1 - Value matches default or key doesn't exist
#
# Output:
#   None
#
# Example:
#   if _flow_config_is_set "timer_default"; then
#     echo "Timer has been customized"
#   fi
#
# Notes:
#   - Uses string comparison between current and default values
#   - Empty/unset values are compared correctly
#   - Useful for showing modified indicators in config display
# =============================================================================
_flow_config_is_set() {
  local key="$1"
  [[ "${FLOW_CONFIG[$key]:-}" != "${FLOW_CONFIG_DEFAULTS[$key]:-}" ]]
}

# ============================================================================
# CONFIG DISPLAY
# ============================================================================

# =============================================================================
# Function: _flow_config_show
# Purpose: Display all configuration values in a formatted, categorized view
# =============================================================================
# Arguments:
#   $1 - (optional) Filter string to match keys/categories
#   $2 - (optional) Show all flag (currently unused) [default: "false"]
#
# Returns:
#   0 - Always succeeds
#
# Output:
#   stdout - Formatted configuration display with:
#     - Header
#     - Categories (CORE, UI, TIMER, ADHD, GIT, AI)
#     - Keys with values
#     - Asterisk (*) for modified values
#     - Config file location
#
# Example:
#   _flow_config_show              # Show all config
#   _flow_config_show "timer"      # Show only timer-related settings
#   _flow_config_show "git"        # Show only git category
#
# Notes:
#   - Values modified from default are marked with asterisk (*)
#   - Filter matches both category names and key names
#   - Uses FLOW_COLORS for formatting
# =============================================================================
_flow_config_show() {
  local filter="${1:-}"
  local show_all="${2:-false}"

  echo ""
  echo "${FLOW_COLORS[header]}FLOW-CLI CONFIGURATION${FLOW_COLORS[reset]}"
  echo ""

  # Group configs by category
  local -A categories=(
    [core]="projects_root atlas_enabled load_dispatchers quiet debug"
    [ui]="color_theme progress_bar_width show_icons"
    [timer]="timer_default timer_break timer_long_break timer_sound"
    [adhd]="auto_breadcrumb session_timeout dopamine_mode"
    [git]="auto_commit commit_emoji push_after_finish"
    [ai]="ai_provider ai_context ai_verbose"
  )

  local -a category_order=(core ui timer adhd git ai)

  for category in "${category_order[@]}"; do
    local keys="${categories[$category]}"
    local -a key_list=(${=keys})

    # Skip if filter doesn't match category
    if [[ -n "$filter" && "$category" != *"$filter"* ]]; then
      local match=false
      for key in "${key_list[@]}"; do
        [[ "$key" == *"$filter"* ]] && match=true && break
      done
      [[ "$match" == "false" ]] && continue
    fi

    echo "  ${FLOW_COLORS[bold]}${category:u}${FLOW_COLORS[reset]}"

    for key in "${key_list[@]}"; do
      # Skip if filter doesn't match
      if [[ -n "$filter" && "$key" != *"$filter"* && "$category" != *"$filter"* ]]; then
        continue
      fi

      local value="${FLOW_CONFIG[$key]:-${FLOW_CONFIG_DEFAULTS[$key]:-}}"
      local default="${FLOW_CONFIG_DEFAULTS[$key]:-}"
      local modified=""

      if [[ "$value" != "$default" ]]; then
        modified=" ${FLOW_COLORS[accent]}*${FLOW_COLORS[reset]}"
      fi

      printf "    %-20s = %s%s\n" "$key" "$value" "$modified"
    done
    echo ""
  done

  echo "${FLOW_COLORS[muted]}  * = modified from default${FLOW_COLORS[reset]}"
  echo "${FLOW_COLORS[muted]}  Config file: $FLOW_CONFIG_FILE${FLOW_COLORS[reset]}"
  echo ""
}

# =============================================================================
# Function: _flow_config_export
# Purpose: Output configuration in a sourceable/exportable format
# =============================================================================
# Arguments:
#   None
#
# Returns:
#   0 - Always succeeds
#
# Output:
#   stdout - Each config key-value pair in FLOW_CONFIG[key]="value" format
#
# Example:
#   # Export to file
#   _flow_config_export > backup-config.zsh
#
#   # Pipe to another process
#   _flow_config_export | grep timer
#
# Notes:
#   - Keys are output in sorted order
#   - Output is directly sourceable by ZSH
#   - Useful for backup, migration, or scripting
# =============================================================================
_flow_config_export() {
  for key in "${(@ko)FLOW_CONFIG}"; do
    echo "FLOW_CONFIG[$key]=\"${FLOW_CONFIG[$key]}\""
  done
}

# ============================================================================
# CONFIG PROFILES
# ============================================================================

# =============================================================================
# Function: _flow_config_profile_list
# Purpose: Display all available configuration profiles (built-in and user)
# =============================================================================
# Arguments:
#   None
#
# Returns:
#   0 - Always succeeds
#
# Output:
#   stdout - Formatted list showing:
#     - Built-in profiles (minimal, developer, adhd, researcher)
#     - User profiles from FLOW_PROFILE_DIR with save dates
#
# Example:
#   _flow_config_profile_list
#   # Output:
#   # CONFIGURATION PROFILES
#   #
#   #   Built-in:
#   #     minimal     - Minimal settings, quiet mode
#   #     developer   - Full developer settings
#   #     ...
#   #   User Profiles:
#   #     myprofile (saved: 2024-01-15)
#
# Notes:
#   - Built-in profiles are hardcoded descriptions
#   - User profiles show modification date from stat
#   - Uses FLOW_COLORS for formatting
# =============================================================================
_flow_config_profile_list() {
  echo ""
  echo "${FLOW_COLORS[header]}CONFIGURATION PROFILES${FLOW_COLORS[reset]}"
  echo ""

  # Built-in profiles
  echo "  ${FLOW_COLORS[bold]}Built-in:${FLOW_COLORS[reset]}"
  echo "    minimal     - Minimal settings, quiet mode"
  echo "    developer   - Full developer settings"
  echo "    adhd        - Maximum ADHD support features"
  echo "    researcher  - Academic workflow optimized"
  echo ""

  # User profiles
  if [[ -d "$FLOW_PROFILE_DIR" ]] && [[ -n "$(ls -A "$FLOW_PROFILE_DIR" 2>/dev/null)" ]]; then
    echo "  ${FLOW_COLORS[bold]}User Profiles:${FLOW_COLORS[reset]}"
    for profile in "$FLOW_PROFILE_DIR"/*.zsh(N); do
      local name="${${profile:t}%.zsh}"
      local modified=$(stat -f "%Sm" -t "%Y-%m-%d" "$profile" 2>/dev/null || echo "unknown")
      echo "    $name (saved: $modified)"
    done
  else
    echo "  ${FLOW_COLORS[muted]}No user profiles saved${FLOW_COLORS[reset]}"
    echo "  ${FLOW_COLORS[muted]}Create with: flow config profile save <name>${FLOW_COLORS[reset]}"
  fi
  echo ""
}

# =============================================================================
# Function: _flow_config_profile_save
# Purpose: Save the current configuration as a named profile
# =============================================================================
# Arguments:
#   $1 - (required) Profile name (alphanumeric, hyphens, underscores)
#
# Returns:
#   0 - Profile saved successfully
#   1 - Error (no name, invalid name, or built-in name)
#
# Output:
#   stdout - Success message with profile file location
#   stderr - Error messages via _flow_log_error
#
# Side Effects:
#   - Creates profile directory if needed
#   - Writes profile file to FLOW_PROFILE_DIR/<name>.zsh
#
# Example:
#   _flow_config_profile_save "work"
#   # Creates ~/.config/flow-cli/profiles/work.zsh
#
# Notes:
#   - Name must start with letter, contain only [a-zA-Z0-9_-]
#   - Cannot overwrite built-in profiles (minimal, developer, adhd, researcher)
#   - Profile includes timestamp comment
# =============================================================================
_flow_config_profile_save() {
  local name="$1"

  if [[ -z "$name" ]]; then
    _flow_log_error "Profile name required"
    return 1
  fi

  # Validate name
  if [[ ! "$name" =~ ^[a-zA-Z][a-zA-Z0-9_-]*$ ]]; then
    _flow_log_error "Invalid profile name. Use letters, numbers, hyphens, underscores."
    return 1
  fi

  # Don't overwrite built-in profile names
  if [[ "$name" == "minimal" || "$name" == "developer" || "$name" == "adhd" || "$name" == "researcher" ]]; then
    _flow_log_error "Cannot overwrite built-in profile: $name"
    return 1
  fi

  local profile_file="$FLOW_PROFILE_DIR/$name.zsh"

  [[ ! -d "$FLOW_PROFILE_DIR" ]] && mkdir -p "$FLOW_PROFILE_DIR"

  # Write profile
  cat > "$profile_file" <<EOF
# flow-cli profile: $name
# Created: $(date -Iseconds)
# Load with: flow config profile load $name

EOF

  for key in "${(@ko)FLOW_CONFIG}"; do
    echo "FLOW_CONFIG[$key]=\"${FLOW_CONFIG[$key]}\"" >> "$profile_file"
  done

  _flow_log_success "Saved profile: $name"
  echo "  Location: $profile_file"
}

# =============================================================================
# Function: _flow_config_profile_load
# Purpose: Load a configuration profile (built-in or user-defined)
# =============================================================================
# Arguments:
#   $1 - (required) Profile name to load
#
# Returns:
#   0 - Profile loaded successfully
#   1 - Error (no name or profile not found)
#
# Output:
#   stdout - Success message and reminder to save
#   stderr - Error messages via _flow_log_error
#
# Side Effects:
#   - Resets FLOW_CONFIG to defaults first
#   - Applies profile-specific settings
#   - Does NOT persist (call _flow_config_save to persist)
#
# Example:
#   _flow_config_profile_load "adhd"      # Load built-in ADHD profile
#   _flow_config_profile_load "mywork"    # Load user profile
#
# Built-in Profiles:
#   minimal    - Quiet mode, no icons, no dopamine features
#   developer  - Full dispatchers, emoji commits, auto context
#   adhd       - Dopamine mode, breadcrumbs, icons, short timers
#   researcher - Long focus timers, long breaks, no auto-push
#
# Notes:
#   - Always resets to defaults before applying profile
#   - User profiles are sourced from FLOW_PROFILE_DIR
#   - Changes are in-memory only until saved
# =============================================================================
_flow_config_profile_load() {
  local name="$1"

  if [[ -z "$name" ]]; then
    _flow_log_error "Profile name required"
    return 1
  fi

  # Handle built-in profiles
  case "$name" in
    minimal)
      _flow_config_reset_all
      FLOW_CONFIG[quiet]="1"
      FLOW_CONFIG[show_icons]="no"
      FLOW_CONFIG[dopamine_mode]="no"
      FLOW_CONFIG[auto_breadcrumb]="no"
      _flow_log_success "Loaded built-in profile: minimal"
      ;;
    developer)
      _flow_config_reset_all
      FLOW_CONFIG[load_dispatchers]="yes"
      FLOW_CONFIG[auto_commit]="no"
      FLOW_CONFIG[commit_emoji]="yes"
      FLOW_CONFIG[ai_context]="auto"
      _flow_log_success "Loaded built-in profile: developer"
      ;;
    adhd)
      _flow_config_reset_all
      FLOW_CONFIG[dopamine_mode]="yes"
      FLOW_CONFIG[auto_breadcrumb]="yes"
      FLOW_CONFIG[show_icons]="yes"
      FLOW_CONFIG[timer_default]="25"
      FLOW_CONFIG[timer_break]="5"
      FLOW_CONFIG[session_timeout]="90"
      _flow_log_success "Loaded built-in profile: adhd"
      ;;
    researcher)
      _flow_config_reset_all
      FLOW_CONFIG[timer_default]="45"
      FLOW_CONFIG[timer_break]="10"
      FLOW_CONFIG[session_timeout]="180"
      FLOW_CONFIG[push_after_finish]="no"
      _flow_log_success "Loaded built-in profile: researcher"
      ;;
    *)
      # Load user profile
      local profile_file="$FLOW_PROFILE_DIR/$name.zsh"

      if [[ ! -f "$profile_file" ]]; then
        _flow_log_error "Profile not found: $name"
        echo "  Available profiles:"
        _flow_config_profile_list
        return 1
      fi

      # Reset to defaults first
      _flow_config_reset_all

      # Source the profile
      source "$profile_file"
      _flow_log_success "Loaded profile: $name"
      ;;
  esac

  echo ""
  echo "${FLOW_COLORS[muted]}Run 'flow config save' to persist changes${FLOW_COLORS[reset]}"
}

# =============================================================================
# Function: _flow_config_profile_delete
# Purpose: Delete a user-defined configuration profile
# =============================================================================
# Arguments:
#   $1 - (required) Profile name to delete
#
# Returns:
#   0 - Profile deleted successfully
#   1 - Error (no name, built-in profile, or not found)
#
# Output:
#   stdout - Success message via _flow_log_success
#   stderr - Error messages via _flow_log_error
#
# Side Effects:
#   - Removes profile file from FLOW_PROFILE_DIR
#
# Example:
#   _flow_config_profile_delete "oldprofile"
#
# Notes:
#   - Cannot delete built-in profiles (minimal, developer, adhd, researcher)
#   - No confirmation prompt (caller should confirm if needed)
#   - File is permanently removed
# =============================================================================
_flow_config_profile_delete() {
  local name="$1"

  if [[ -z "$name" ]]; then
    _flow_log_error "Profile name required"
    return 1
  fi

  # Don't delete built-in profiles
  if [[ "$name" == "minimal" || "$name" == "developer" || "$name" == "adhd" || "$name" == "researcher" ]]; then
    _flow_log_error "Cannot delete built-in profile: $name"
    return 1
  fi

  local profile_file="$FLOW_PROFILE_DIR/$name.zsh"

  if [[ ! -f "$profile_file" ]]; then
    _flow_log_error "Profile not found: $name"
    return 1
  fi

  rm "$profile_file"
  _flow_log_success "Deleted profile: $name"
}

# ============================================================================
# INTERACTIVE CONFIG
# ============================================================================

# =============================================================================
# Function: _flow_config_wizard
# Purpose: Run an interactive configuration wizard for common settings
# =============================================================================
# Arguments:
#   None
#
# Returns:
#   0 - Always succeeds
#
# Output:
#   stdout - Interactive prompts for each setting
#   stdin  - Reads user input for each setting
#
# Side Effects:
#   - Modifies FLOW_CONFIG values based on user input
#   - Optionally saves config via _flow_config_save
#
# Example:
#   _flow_config_wizard
#   # Walks through: projects_root, atlas_enabled, quiet, timer_default,
#   # timer_break, dopamine_mode, auto_breadcrumb, push_after_finish,
#   # commit_emoji
#
# Notes:
#   - Press Enter to keep current value
#   - Groups settings by category (Core, Timer, ADHD, Git)
#   - Uses _flow_confirm for save confirmation
#   - Emoji wizard header (intentional for ADHD appeal)
# =============================================================================
_flow_config_wizard() {
  echo ""
  echo "${FLOW_COLORS[header]}🔧 FLOW-CLI CONFIGURATION WIZARD${FLOW_COLORS[reset]}"
  echo ""
  echo "This wizard will help you configure flow-cli."
  echo "Press Enter to keep the current value."
  echo ""

  # Core settings
  echo "${FLOW_COLORS[bold]}CORE SETTINGS${FLOW_COLORS[reset]}"

  local current value

  # Projects root
  current="${FLOW_CONFIG[projects_root]}"
  echo -n "  Projects root [$current]: "
  read -r value
  [[ -n "$value" ]] && FLOW_CONFIG[projects_root]="$value"

  # Atlas enabled
  current="${FLOW_CONFIG[atlas_enabled]}"
  echo -n "  Atlas integration (auto/yes/no) [$current]: "
  read -r value
  [[ -n "$value" ]] && FLOW_CONFIG[atlas_enabled]="$value"

  # Quiet mode
  current="${FLOW_CONFIG[quiet]}"
  echo -n "  Quiet mode (0/1) [$current]: "
  read -r value
  [[ -n "$value" ]] && FLOW_CONFIG[quiet]="$value"

  echo ""
  echo "${FLOW_COLORS[bold]}TIMER SETTINGS${FLOW_COLORS[reset]}"

  # Timer default
  current="${FLOW_CONFIG[timer_default]}"
  echo -n "  Default timer (minutes) [$current]: "
  read -r value
  [[ -n "$value" ]] && FLOW_CONFIG[timer_default]="$value"

  # Break timer
  current="${FLOW_CONFIG[timer_break]}"
  echo -n "  Break timer (minutes) [$current]: "
  read -r value
  [[ -n "$value" ]] && FLOW_CONFIG[timer_break]="$value"

  echo ""
  echo "${FLOW_COLORS[bold]}ADHD SETTINGS${FLOW_COLORS[reset]}"

  # Dopamine mode
  current="${FLOW_CONFIG[dopamine_mode]}"
  echo -n "  Dopamine mode (yes/no) [$current]: "
  read -r value
  [[ -n "$value" ]] && FLOW_CONFIG[dopamine_mode]="$value"

  # Auto breadcrumb
  current="${FLOW_CONFIG[auto_breadcrumb]}"
  echo -n "  Auto breadcrumb (yes/no) [$current]: "
  read -r value
  [[ -n "$value" ]] && FLOW_CONFIG[auto_breadcrumb]="$value"

  echo ""
  echo "${FLOW_COLORS[bold]}GIT SETTINGS${FLOW_COLORS[reset]}"

  # Push after finish
  current="${FLOW_CONFIG[push_after_finish]}"
  echo -n "  Push after finish (yes/no/ask) [$current]: "
  read -r value
  [[ -n "$value" ]] && FLOW_CONFIG[push_after_finish]="$value"

  # Commit emoji
  current="${FLOW_CONFIG[commit_emoji]}"
  echo -n "  Use emoji in commits (yes/no) [$current]: "
  read -r value
  [[ -n "$value" ]] && FLOW_CONFIG[commit_emoji]="$value"

  echo ""

  # Save
  if _flow_confirm "Save configuration?"; then
    _flow_config_save
    _flow_log_success "Configuration saved!"
  else
    echo "Configuration not saved. Changes will be lost on shell restart."
  fi
}

# ============================================================================
# APPLY CONFIG TO ENVIRONMENT
# ============================================================================

# =============================================================================
# Function: _flow_config_apply
# Purpose: Apply configuration values to environment variables
# =============================================================================
# Arguments:
#   None
#
# Returns:
#   0 - Always succeeds
#
# Output:
#   None
#
# Side Effects:
#   - Exports FLOW_PROJECTS_ROOT from config or default
#   - Exports FLOW_ATLAS_ENABLED from config or default
#   - Exports FLOW_LOAD_DISPATCHERS from config or default
#   - Sets FLOW_QUIET=1 if config[quiet]="1"
#   - Sets FLOW_DEBUG=1 if config[debug]="1"
#
# Example:
#   _flow_config_apply
#   echo $FLOW_PROJECTS_ROOT  # => /home/user/projects
#
# Notes:
#   - Maps internal config keys to exported environment variables
#   - Called after config load to sync environment
#   - Boolean configs (quiet, debug) only set if "1", not unset otherwise
# =============================================================================
_flow_config_apply() {
  # Map config values to environment variables
  export FLOW_PROJECTS_ROOT="${FLOW_CONFIG[projects_root]:-$HOME/projects}"
  export FLOW_ATLAS_ENABLED="${FLOW_CONFIG[atlas_enabled]:-auto}"
  export FLOW_LOAD_DISPATCHERS="${FLOW_CONFIG[load_dispatchers]:-yes}"

  [[ "${FLOW_CONFIG[quiet]}" == "1" ]] && export FLOW_QUIET=1
  [[ "${FLOW_CONFIG[debug]}" == "1" ]] && export FLOW_DEBUG=1
}

# ============================================================================
# INITIALIZATION
# ============================================================================

# Auto-initialize on source
_flow_config_init
